# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
# Copy the entire project to the working directory
COPY ./mnist-service .
COPY ./proto ./proto

# Install app dependencies
RUN npm install

# Define the command to run your app using node
CMD [ "node", "server.js" ]