/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: proto/server_def.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./server_def_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.MnistServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.MnistServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.MnistRequest,
 *   !proto.MnistResponse>}
 */
const methodDescriptor_MnistService_GetImage = new grpc.web.MethodDescriptor(
  '/MnistService/GetImage',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.MnistRequest,
  proto.MnistResponse,
  /**
   * @param {!proto.MnistRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.MnistResponse.deserializeBinary
);


/**
 * @param {!proto.MnistRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.MnistResponse>}
 *     The XHR Node Readable Stream
 */
proto.MnistServiceClient.prototype.getImage =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/MnistService/GetImage',
      request,
      metadata || {},
      methodDescriptor_MnistService_GetImage);
};


/**
 * @param {!proto.MnistRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.MnistResponse>}
 *     The XHR Node Readable Stream
 */
proto.MnistServicePromiseClient.prototype.getImage =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/MnistService/GetImage',
      request,
      metadata || {},
      methodDescriptor_MnistService_GetImage);
};


module.exports = proto;

